### PR TITLE
ft: add the MIME type for markdown files

### PR DESCRIPTION
**Pull request by jasmineleonard**
Adds the MIME type for markdown files.

https://www.iana.org/assignments/media-types/text/markdown

### CODE REVIEW

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by thiamsantos** [comment]
Hello, would be possible to release a new version of the library with this change?

**Comment by josevalim** [comment]
done!

**Comment by thiamsantos** [comment]
Thank you :heart:

**Pull request merged**
